best_value: 1.0809
best_params:
  dropout_prob: 0.4395881692124673
  n_layers: 4
  l0_nodes: 112
  l1_nodes: 76
  l2_nodes: 27
  l3_nodes: 39
  l0_activation: gelu
  l1_activation: relu
  l2_activation: softplus
  l3_activation: leakyrelu
  learning_rate: 0.0005649302491006826
  batch_size: 2
  n_epochs: 500
